### Get all tasks
GET http://localhost:3001/tasks

### Get task by id
GET http://localhost:3001/tasks/a603aa66-970f-4b6b-8bf3-b3457a589a74

### Get tasks by filter
GET http://localhost:3001/tasks?filter=PENDING

### Get tasks by user id
GET http://localhost:3001/tasks/user/12345678

### Create task
POST http://localhost:3001/tasks
Content-Type: application/json

{
  "title": "Complete project documentation",
  "description": "Write comprehensive documentation for the Task Manager API"
}


### Update task
PUT http://localhost:3001/tasks/a603aa66-970f-4b6b-8bf3-b3457a589a74
Content-Type: application/json

{
  "status": "PENDING",
  "userId": 1234567
}

### Delete task
DELETE http://localhost:3001/tasks/a603aa66-970f-4b6b-8bf3-b3457a589a74