### Get all tasks
GET http://localhost:3001/tasks

### Get task by id
GET http://localhost:3001/tasks/e47ac9de-af97-4e0c-b9c2-dee2689e205d

### Get tasks by filter
GET http://localhost:3001/tasks?filter=PENDING

### Get tasks by user id
GET http://localhost:3001/tasks/user/0aa5fc14-8077-4981-a381-e5c068be9ef6

### Create task
POST http://localhost:3001/tasks
Content-Type: application/json

{
  "title": "Complete project documentation",
  "description": "Write comprehensive documentation for the Task Manager API",
  "status": "PENDING",
  "userId": "0aa5fc14-8077-4981-a381-e5c068be9ef6"
}


### Update task
PUT http://localhost:3001/tasks/e47ac9de-af97-4e0c-b9c2-dee2689e205d
Content-Type: application/json

{
  "status": "DONE"
}

### Delete task
DELETE http://localhost:3001/tasks/e47ac9de-af97-4e0c-b9c2-dee2689e205d